//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneProdotti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compagnia
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    
        public virtual Indirizzo Indirizzo { get; set; }
        public virtual MezzoContatto MezzoContatto { get; set; }
        public virtual Prodotto Prodotto { get; set; }
    }
}
