//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneProdotti.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompagnieProdottiEntities : DbContext
    {
        public CompagnieProdottiEntities()
            : base("name=CompagnieProdottiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaMerceologica> CategoriaMerceologica { get; set; }
        public virtual DbSet<Compagnia> Compagnia { get; set; }
        public virtual DbSet<Indirizzo> Indirizzo { get; set; }
        public virtual DbSet<MezzoContatto> MezzoContatto { get; set; }
        public virtual DbSet<Prodotto> Prodotto { get; set; }
    }
}
