//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestioneProdotti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prodotto
    {
        public int IdCompagnia { get; set; }
        public string Nome { get; set; }
        public string CategoriaMerceologica { get; set; }
    
        public virtual CategoriaMerceologica CategoriaMerceologica1 { get; set; }
        public virtual Compagnia Compagnia { get; set; }
    }
}
